server {
    listen 80;
    
    root /usr/share/nginx/html;
    index index.html;

    # Disable cache for index.html to ensure users always get the latest version
    location /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
    
    # Optional: Cache static assets for a long time
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public";
    }
}
